### ISSUE TITLE
Performance of iCaRL implementation

### ISSUE THREAD

**Issue by 18908513552** [NiccoloCavagnero/IncrementalLearning#1]
Dear author, I find the performance of your iCaRL implementation is lower than the original paper. Would you please tell me the reason？

**Comment by NiccoloCavagnero** [comment]
Hi, we actually do not know why the performances are lower. It may be 
due to a different order in the classes. If you notice differences at 
implementation level (besides herding which we found useless) please 
tell me!

Good work,
Niccolò

Il 2021-09-18 08:27 ZY Zhang ha scritto:

**Comment by UntitledPro** [comment]
Dear author, why do you flip the images in the code of iCaRL, this operation seems not to be mentioned in the original paper. Could you please tell me why?⊙﹏⊙∥

**Comment by NiccoloCavagnero** [comment]
It’s standard practice to horizontally flip the images in order to 
augment the dataset. However, if I’m not mistaken there is a mention to 
it in the paper.

Good work,
Niccolò

Il 2021-10-24 05:09 Eidolon ha scritto:
